### ISSUE TITLE
Initialize Charts project

### ISSUE THREAD

**Issue by zzvara** [selenium-monitoring/charts#1]
- [ ] [Find the `charts`](https://github.com/Mliviusz/szakdolgozat) and upload code to `charts` repository (if exists).
- [ ] Migrate Github CI as well.
- [ ] In case you find plain Kubernetes YAML files, run the operator on your Kubernetes installation using the provided YAML files.

**Comment by balinthegyi** [comment]
There is no hem chart in the Líviusz projekt.
